"""Shared utility functions for pi_coding."""

from pi_coding.utils.edit_diff import (
    EditDiffError,
    EditDiffResult,
    FuzzyMatchResult,
    compute_edit_diff,
    detect_line_ending,
    fuzzy_find_text,
    generate_diff_string,
    normalize_for_fuzzy_match,
    normalize_to_lf,
    restore_line_endings,
    strip_bom,
)
from pi_coding.utils.git import (
    GitSource,
    get_current_branch,
    get_repo_status,
    parse_git_url,
)
from pi_coding.utils.path_utils import (
    UNICODE_SPACES,
    expand_path,
    file_exists,
    normalize_at_prefix,
    normalize_unicode_spaces,
    resolve_read_path,
    resolve_to_cwd,
    try_curly_quote_variant,
    try_macos_screenshot_path,
    try_nfd_variant,
)
from pi_coding.utils.shell import (
    get_shell_config,
    get_shell_env,
    kill_process_tree,
    sanitize_binary_output,
)
from pi_coding.utils.truncate import (
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_LINES,
    GREP_MAX_LINE_LENGTH,
    TruncationOptions,
    TruncationResult,
    format_size,
    truncate_head,
    truncate_line,
    truncate_tail,
)

__all__ = [
    "EditDiffError",
    "EditDiffResult",
    "FuzzyMatchResult",
    "compute_edit_diff",
    "detect_line_ending",
    "fuzzy_find_text",
    "generate_diff_string",
    "normalize_for_fuzzy_match",
    "normalize_to_lf",
    "restore_line_endings",
    "strip_bom",
    "GitSource",
    "get_current_branch",
    "get_repo_status",
    "parse_git_url",
    "UNICODE_SPACES",
    "expand_path",
    "file_exists",
    "normalize_at_prefix",
    "normalize_unicode_spaces",
    "resolve_read_path",
    "resolve_to_cwd",
    "try_curly_quote_variant",
    "try_macos_screenshot_path",
    "try_nfd_variant",
    "get_shell_config",
    "get_shell_env",
    "kill_process_tree",
    "sanitize_binary_output",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_LINES",
    "GREP_MAX_LINE_LENGTH",
    "TruncationOptions",
    "TruncationResult",
    "format_size",
    "truncate_head",
    "truncate_line",
    "truncate_tail",
]
